# typical project.yml template
# make a copy of this for each project and adjust the parameters accordingly

species: "path_to_species_list/species.lst"
maf_path: "path_to_mafs/"
phast_path: "path_to_phast/phast/bin/"
gtf_path: "path_to_chromosome_gtfs/hg38_gtf_files"
outdir: "output_dir/outfiles"
init_tree: "initial_newick_tree/hg38.100way.nh"
species_of_interest: "hg38"
chrom_bed_path: "path_to_chrom_sizes_beds/chrom_beds/"
synteny_filter_dog: "path_to_dog_synteny/dog_hg38.sorted.bed.gz" 
synteny_filter_rhesus: "path_to_rhesus_synteny/rhesus_hg38.sorted.bed.gz" 
synteny_filter_mouse: "path_to_mouse_synteny/mouse_hg38.sorted.bed.gz" 
ar_filters_path: "path_to_filters/har_filters.sorted.bed.gz"
n_phylop_chunks: "100"
max_p: "0.01"
random_seed: "1"